# Generated by Django 2.2.13 on 2020-10-05 00:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_eveonline_doctrine_manager', '0006_auto_20201005_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evedoctrinemanagerbaseobject',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='everequiredskill',
            name='skill_for',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='django_eveonline_doctrine_manager.EveDoctrineManagerBaseObject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='everequiredskill',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
